replicaCount: 1

image:
  repository: 761406923746.dkr.ecr.ap-northeast-2.amazonaws.com/terry
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: awsecr-cred

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  hosts:
    - host: fast-api.test
      paths: []
  tls: []

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}