# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 761406923746.dkr.ecr.ap-northeast-2.amazonaws.com/terry
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: awsecr-cred

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: fast-api.test
      paths:
        - path: /
          pathType: Prefix

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi
